name: build and test on android
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test-in-android-emulator:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: add NDK toolchain to path
        run: |
            echo "$ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH
      - name: git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: install rust toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          # aarch64 feature detection is stable
          toolchain: stable
          target: aarch64-linux-android
          components: clippy
      - name: cache rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: cargo build for aarch64-linux-android
        run: |
            cargo +${{ steps.toolchain.outputs.name }} build --target aarch64-linux-android --release
        env:
          AR: llvm-ar
          CC: aarch64-linux-android26-clang
          RUSTFLAGS: "-C linker=aarch64-linux-android26-clang -L $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/17/lib/linux/aarch64 -L $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/26"
