name: build and test on arm7 with QEMU
on: [push, pull_request]
jobs:
  test-on-qemu-linux-arm7:
    runs-on: ubuntu-latest
    name: test on debian-bullseye-arm7
    steps:
      - name: install prerequisites
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: g++-arm-linux-gnueabihf libc6-dev-armhf-cross
          version: 1.0 # version of cache to load
      - name: git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: set up qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm
      - name: cache rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: arm7-unknown-linux-gnu-cargo-and-target-${{ hashFiles('**/Cargo.lock') }}
      # - name: cache dav1d object files
      #   uses: actions/cache@v3
      #   with:
      #     path: build/
      #     key: aarch64-unknown-linux-gnu-c-object-files-${{ hashFiles('**/meson.build', '**/*.c', '**/*.h') }}
      - name: cargo build for armv7-unknown-linux-gnueabihf
        run: |
          rustup target add armv7-unknown-linux-gnueabihf
          cargo build --release --target armv7-unknown-linux-gnueabihf
      - name: docker pull
        run: docker pull ghcr.io/immunant/rav1d/debian-bullseye-arm7:latest
      - name: build and run tests in docker
        run: |
          docker run \
            --rm \
            -v ~/.cargo/git:/home/prossimo/.cargo/git \
            -v ~/.cargo/registry:/home/prossimo/.cargo/registry \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/arm/v7 \
            ghcr.io/immunant/rav1d/debian-bullseye-arm7:latest \
            .github/workflows/test.sh -t 2 \
                -r ../target/armv7-unknown-linux-gnueabihf/release/dav1d \
                -s ../target/armv7-unknown-linux-gnueabihf/release/seek_stress
      - name: upload build artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v3
        with:
          name: meson-test-logs
          path: |
             ${{ github.workspace }}/build/meson-logs/testlog.txt